### PR TITLE
New spam hosts + new configuration file format

### PR DESCRIPTION
**Pull request by bluszcz**
Extracted from my jabberpl.org server.

### CODE REVIEW

**Comment by bluszcz** [comment]
Updated PR.

**Comment by agx** [comment]
@bluszcz Thanks!

**Comment by agx** [comment]
@bluszcz I've moved everything to a single list and generate both config formats from it. Could you check if generated/blacklist.yml still works as expected?

**Comment by bluszcz** [comment]
Seems it works ok.

**Comment by agx** [comment]
@bluszcz thanks for checking!

**Pull request merged**
